podTemplate(containers: [
  containerTemplate(
    name: 'gradle',
    image: 'gradle:6.3-jdk14',
    command: 'sleep',
      args: '30d'),
]) {
  node(POD_LABEL) {
    stage('Run pipeline against a gradle project') {
      git 'https://github.com/harvash/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
      container('gradle') {
        stage('Build a gradle project') {
          if (env.BRANCH_NAME == 'main') {
            sh '''cd Chapter08/sample1
                  chmod +x gradlew
                  ./gradlew test''' 
          }
        }
        stage('Code coverage') {
          if (env.BRANCH_NAME == 'main') {
            sh '''pwd
                  cd Chapter08/sample1
                  ./gradlew jacocoTestCoverageVerification
                  ./gradlew jacocoTestReport'''
            publishHTML (
              target: [
                reportDir: 'Chapter08/sample1/build/reports/jacoco/test/html',
                reportFiles: 'index.html',
                reportName: 'JaCoCo Report'
              ]
            )
          }
        }
        stage('Checkstyle') {
          if (env.BRANCH_NAME == 'feature') {
            try {
              sh '''pwd
                    cd Chapter08/sample1
                    ./gradlew checkstyleMain'''
            } catch(all) {
                echo "checkstyle fails"
            }
            publishHTML (
              target: [
                reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                reportFiles: 'main.html',
                reportName: 'CheckStyle Report'
              ]
            )
          }
        }
        stage('Unit_test') {
          if (env.BRANCH_NAME == 'feature') {
            try {
              sh '''pwd
                    cd Chapter08/sample1
                    ./gradlew test'''
            } catch(all) {
                echo "Unit tests fail"
            }
          }
        }
      }
    }
  }
}